### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by Zireael07** [Adellica/Thumbkeyboard#2]
Title

**Comment by kristianlm** [comment]
Hi,

There is a apk binary available from the releases if that's what you're looking for:

https://github.com/kristianlm/Thumbkeyboard/releases

It's a bit outdated, but might help if you just want to try it out. Note that it's a debug-build.

**Comment by Zireael07** [comment]
Yeah, it works thanks! (You might want to put the link somewhere prominent on the github repo and/or the README, I don't know why but Github doesn't show the normal releases tab here)
